### ISSUE TITLE
MDA Engine cannot be cancelled after an error

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/pymmcore-plus#130]
If you have an error in a callback to `frameReady` then it becomes impossible to start a new MDA as the previous one was never finished. 
Either it should be made more robust to those errors - or it should catch them and finish (emitting a signal that it failed etc)

Example:

```python
from useq import MDASequence, MDAEvent
import numpy as np

from pymmcore_plus import CMMCorePlus

# get the Core singleton
mmc = CMMCorePlus.instance()

# load the demo config
mmc.loadSystemConfiguration()


# Define the MDA
sequence = MDASequence(
    channels=["DAPI", {"config": "FITC", "exposure": 50}],
    time_plan={"interval": 2, "loops": 5},
    z_plan={"range": 4, "step": 0.5},
    axis_order="tpcz",
)
@mmc.mda.events.frameReady.connect
def frameReady(img: np.ndarray, event: MDAEvent):
    raise ValueError("oh no")
mmc.run_mda(sequence).join()
mmc.run_mda(sequence)
```

gives:

```
2022-05-24 15:00:39.898 | DEBUG    | pymmcore_plus._util:find_micromanager:47 - using MM path found in applications: /usr/local/lib/micro-manager
2022-05-24 15:00:39.899 | INFO     | pymmcore_plus.core._mmcore_plus:setDeviceAdapterSearchPaths:152 - setting adapter search paths: ['/usr/local/lib/micro-manager']
2022-05-24 15:00:39.905 | INFO     | pymmcore_plus.mda._engine:_prepare_to_run:122 - MDA Started: Multi-Dimensional Acquisition ▶ nt: 5, np: 0, nc: 2, nz: 9
2022-05-24 15:00:39.907 | INFO     | pymmcore_plus.mda._engine:run:260 - metadata={} index={'t': 0, 'c': 0, 'z': 0} channel=Channel(config='DAPI') exposure=None min_start_time=0.0 x_pos=None y_pos=None z_pos=-2.0 properties=None
Exception in thread Thread-5 (run):
Traceback (most recent call last):
  File "/home/ian/mambaforge/envs/pymm/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/ian/mambaforge/envs/pymm/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ian/Documents/oss/micro/pymmcore-plus/pymmcore_plus/mda/_engine.py", line 266, in run
    self._events.frameReady.emit(img, event)
  File "psygnal/_signal.py", line 681, in psygnal._signal.SignalInstance.emit
  File "psygnal/_signal.py", line 723, in psygnal._signal.SignalInstance._run_emit_loop
  File "psygnal/_signal.py", line 724, in psygnal._signal.SignalInstance._run_emit_loop
  File "psygnal/_signal.py", line 744, in psygnal._signal.SignalInstance._run_emit_loop
  File "/tmp/ipykernel_221079/292189580.py", line 22, in frameReady
ValueError: oh no

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 24>()
     22     raise ValueError("oh no")
     23 mmc.run_mda(sequence).join()
---> 24 mmc.run_mda(sequence)

File ~/Documents/oss/micro/pymmcore-plus/pymmcore_plus/core/_mmcore_plus.py:578, in CMMCorePlus.run_mda(self, sequence)
    560 """
    561 Run MDA defined by *sequence* on a new thread. The currently
    562 registered MDAEngine (``core.mda``) will be responsible for executing
   (...)
    575     The thread the MDA is running on.
    576 """
    577 if self._mda_engine.is_running():
--> 578     raise ValueError(
    579         "Cannot start an MDA while the previous MDA is still running."
    580     )
    581 th = Thread(target=self._mda_engine.run, args=(sequence,))
    582 th.start()

ValueError: Cannot start an MDA while the previous MDA is still running.
```

**Comment by ianhi** [comment]
Calling `core.mda.cancel()` will have no effect as the waiting loop is no longer running so the check for being cancelled never gets run.

**Comment by ianhi** [comment]
Fixed by: https://github.com/pymmcore-plus/pymmcore-plus/pull/133
