### ISSUE TITLE
Look deeper into whether our shared logging strategy is ok or error prone

### ISSUE THREAD

**Issue by tlambert03** [pymmcore-plus/pymmcore-plus#385]
output from two competing logging threads,  one from python logger and the other from CMMCore logger:

```
2024-10-09T15:37:39.149360 tid0x1716c3000 [IFO,App] msg 0 from core
2024-10-09T15:37:39.149    tid0x1726cf000 [INFO,pymmcore-plus] info 0 from python
2024-10-09T15:37:39.151    tid0x1726cf000 [INFO,pymmcore-plus] info 1 from python
2024-10-09T15:37:39.154    tid0x1726cf000 [INFO,pymmcore-plus] info 2 from python
2024-10-09T15:37:39.154    tid0x1726cf000 [INFO,pymmcore-plus] info 3 from python
2024-10-09T15:37:39.154    tid0x1726cf000 [INFO,pymmcore-plus] info 4 from python
2024-10-09T15:37:39.155    tid0x1726cf000 [INFO,pymmcore-plus] info 5 from python
2024-10-09T15:37:39.155    tid0x1726cf000 [INFO,pymmcore-plus] info 6 from python
2024-10-09T15:37:39.155    tid0x1726cf000 [INFO,pymmcore-plus] info 7 from python
2024-10-09T15:37:39.155    tid0x1726cf000 [INFO,pymmcore-plus] info 8 from python
2024-10-09T15:37:39.155    tid0x1726cf000 [INFO,pymmcore-plus] info 9 from python
2024-10-09T15:37:39.155    tid0x1726cf000 [INFO,pymmcore-plus] info 10 from python
2024-10-09T15:37:39.156    tid0x1726cf000 [INFO,pymmcore-plus] info 11 from python
2024-10-09T15:37:39.156    tid0x1726cf000 [INFO,pymmcore-plus] info 12 from python
2024-10-09T15:37:39.149841 tid0x1716c3000 [IFO,App] msg 1 from core
2024-10-09T15:37:39.149844 tid0x1716c3000 [IFO,App] msg 2 from core
2024-10-09T15:37:39.149846 tid0x1716c3000 [IFO,App] msg 3 from core
2024-10-09T15:37:39.149847 tid0x1716c3000 [IFO,App] msg 4 from core
2024-10-09T15:37:39.149848 tid0x1716c3000 [IFO,App] msg 5 from core
2024-10-09T15:37:39.149866 tid0x1716c3000 [IFO,App] msg 6 from core
2024-10-09T15:37:39.150373 tid0x1716c3000 [IFO,App] msg 7 from core
2024-10-09T15:37:39.150375 tid0x1716c3000 [IFO,App] msg 8 from core
2024-10-09T15:37:39.150376 tid0x1716c3000 [IFO,App] msg 9 from core
2024-10-09T15:37:39.150376 tid0x1716c3000 [IFO,App] msg 10 from core
2024-10-09T15:37:39.150408 tid0x1716c3000 [IFO,App] msg 11 from core
2024-10-09T15:37:39.150415 tid0x1716c3000 [IFO,App] msg 12 from core
2024-10-09T15:37:39.150415 tid0x1716c3000 [IFO,App] msg 13 from core
2024-10-09T15:37:39.150416 tid0x1716c3000 [IFO,App] msg 14 from core
2024-10-09T15:37:39.150416 tid0x1716c3000 [IFO,App] msg 15 from core
2024-10-09T15:37:39.150417 tid0x1716c3000 [IFO,App] msg 16 from core
2024-10-09T15:37:39.150417 tid0x1716c3000 [IFO,App] msg 17 from core
2024-10-09T15:37:39.150418 tid0x1716c3000 [IFO,App] msg 18 from core
2024-10-09T15:37:39.151430 tid0x1716c3000 [IFO,App] msg 19 from core
2024-10-09T15:37:39.151933 tid0x1716c3000 [IFO,App] msg 20 from core
2024-10-09T15:37:39.156    tid0x1726cf000 [INFO,pymmcore-plus] info 13 from python
2024-10-09T15:37:39.162    tid0x1726cf000 [INFO,pymmcore-plus] info 14 from python
2024-10-09T15:37:39.163    tid0x1726cf000 [INFO,pymmcore-plus] info 15 from python
2024-10-09T15:37:39.163    tid0x1726cf000 [INFO,pymmcore-plus] info 16 from python
2024-10-09T15:37:39.163    tid0x1726cf000 [INFO,pymmcore-plus] info 17 from python
2024-10-09T15:37:39.163    tid0x1726cf000 [INFO,pymmcore-plus] info 18 from python
2024-10-09T15:37:39.163    tid0x1726cf000 [INFO,pymmcore-plus] info 19 from python
2024-10-09T15:37:39.163    tid0x1726cf000 [INFO,pymmcore-plus] info 20 from python
```

note that the absolute time stamp is incorrectly ordered.  

possible solutions:
- just have the pymmcore plus logger log to a different file (not really a solution, more of an all out avoidance)
- rather than using the python logger `logger.info('msg')`, always go through the core logger instead.  This could look something like `CMMCorePlus.instance().logMessage(msg)` ... however that does get possibly sticky in that it makes assumptions about using the global singleton at `CMMCorePlus.instance()`

cc @marktsuchida @nicost

**Comment by wl-stepp** [comment]
No sure if this is related, but we get a lot of PermissionErrors.
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\logging\handlers.py", line 74, in emit
    self.doRollover()
  File "C:\Program Files\Python311\Lib\logging\handlers.py", line 179, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python311\Lib\logging\handlers.py", line 115, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\stepp\\AppData\\Local\\pymmcore-plus\\pymmcore-plus\\logs\\pymmcore-plus.log' -> 'C:\\Users\\stepp\\AppData\\Local\\pymmcore-plus\\pymmcore-plus\\logs\\pymmcore-plus.log.1'
Call stack:
  File "C:\Program Files\Python311\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Control_2\.venv\Lib\site-packages\pymmcore_plus\mda\_runner.py", line 201, in run
    self._run(engine, events)
  File "C:\Control_2\.venv\Lib\site-packages\pymmcore_plus\mda\_runner.py", line 290, in _run
    logger.info("%s", event)
```
I can't tell why yet. No other process is running, but an earlier crash might well be.
